name: setting up environment

on: [push]
    
env:
  username: Area69Lab   # This Repository Username

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        # Change these values if you have forked it for your own works
        run: |
          git config --global user.name "ElytrA8"
          git config --global user.email "manofuranium@gmail.com"

      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${{ secrets.GHUSER }}:${{ secrets.GHPASS }}@github.com/${{ secrets.REPOM }} source
      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls
      - name: running Docker
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i mirror-bot
      - name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://github.com/$username/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > loop.txt
          git add loop.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GHPASS }}@github.com/${GITHUB_REPOSITORY} HEAD:main
